# **Sesión 1:** Introducción a OpenCV y Espacios de color ⚙️🖼️ 

Cristina Hernandez, Macarena Vargas, Beatriz Jimenez 

## 0. Preparación

In [1]:
import cv2, numpy as np, matplotlib.pyplot as plt
import os
import cv2
import imageio
import numpy as np
from typing import List
from utils import get_hsv_color_ranges
import glob

## **Apartado A: Uso basico de funciones de OpenCV**



El objetivo de este apartado es aprender a usar funcionalidades basica sobre el uso de OpenCV, para ello se hara uso de las imágenes en la carpeta ``data``.

1. **Tarea A.1**. Cargar una imagen ``cv2.imread()``.
2. **Tarea A.2.** Visualizar una imagen ``cv2.imshow()``.
3. **Tarea A.3.** Conversion de imagen de color a escala de grises ``cv2.cvtColor()``.
4. **Tarea A.4.** Cambia el tamaño de una imagen ``cv2.resize()`` a 200x200 píxeles.
5. **Tarea A.5.** Recorta el centro de la imagen a un tamaño 120x160.
6. **Tarea A.6.** Rota la imagen ``cv2.getRotationMatrix2D`` ``cv2.wrapAffine()``.
7. **Tarea A.7.** Guarda la imagen ``cv2.imwrite()``.

### **Tarea A.1:** Cargar una imagen con ``cv2.imread()``

In [2]:
# TODO: Load an image from disk using cv2.imread('path/to/image.jpg').
img = cv2.imread("../data/000.jpg")
print(img)

[[[ 91 131 103]
  [ 86 126 101]
  [ 75 118  97]
  ...
  [ 47  86  41]
  [ 47  83  39]
  [ 44  80  36]]

 [[ 90 129 103]
  [ 87 127 102]
  [ 78 119  98]
  ...
  [ 52  90  48]
  [ 50  88  46]
  [ 47  85  43]]

 [[ 91 127 103]
  [ 87 126 104]
  [ 79 122 101]
  ...
  [ 55  97  56]
  [ 53  95  54]
  [ 52  92  51]]

 ...

 [[  9  82 120]
  [  5  78 116]
  [  2  72 112]
  ...
  [  0  30  19]
  [  0  30  19]
  [  0  30  19]]

 [[  6  71 115]
  [  3  68 112]
  [  0  65 110]
  ...
  [  0  28  19]
  [  0  28  19]
  [  0  28  19]]

 [[  0  53 102]
  [  0  55 104]
  [  0  61 109]
  ...
  [  0  26  20]
  [  0  26  20]
  [  0  26  20]]]


### **Tarea A.2:** Visualizar la imagen con ``cv2.imshow()``


In [3]:
# TODO: Display the image using cv2.imshow().
cv2.imshow("mat", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### **Tarea A.3:** Conversion de imagen de color a escala de grises ``cv2.cvtColor()``.

In [4]:
# TODO: Convert the image from color to grayscale using cv2.cvtColor().
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# TODO: Check image shape → grayscale: (height, width), color: (height, width, channels).
print("Color shape:", img.shape)
print("Gray shape:", gray.shape)
# TODO: Display the image using cv2.imshow().
cv2.imshow("gray image", gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

Color shape: (184, 275, 3)
Gray shape: (184, 275)


### **Tarea A.4:** Cambia el tamaño de una imagen ``cv2.resize()`` a 200x200 píxeles.

In [5]:
# TODO: Resize the image to 200×200 pixels using cv2.resize().
resized = cv2.resize(img, (200, 200))
# TODO: Check the image shape
print("Resized shape:", resized.shape)
# TODO: Display the image using cv2.imshow().
cv2.imshow("resized image", resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

Resized shape: (200, 200, 3)


### **Tarea A.5:** Recorta el centro de la imagen a un tamaño 120x160.

In [6]:
# TODO: # TODO: Crop the center of the image 'img' with an approximate size of 120x160 pixels.
h, w = img.shape[:2]
cy, cx =  h // 2, w // 2
roi = img[cy-60:cy+60, cx-80:cx+80]
# TODO: Check the image shape
print("ROI shape:", roi.shape)
# TODO: Display the image using cv2.imshow().
cv2.imshow("ROI", roi)
cv2.waitKey(0)
cv2.destroyAllWindows()

ROI shape: (120, 160, 3)


### **Tarea A.6:** Rota la imagen usando ``cv2.getRotationMatrix2D`` y ``cv2.wrapAffine()``.

In [7]:
# TODO: Rotate around the center using cv2.getRotationMatrix2D and cv2.warpAffine.
h, w = img.shape[:2]
center = (cx, cy)


M = cv2.getRotationMatrix2D(center, 45, 1.0)
rotated = cv2.warpAffine(img, M, (w, h))
# TODO: Display the image using cv2.imshow().
cv2.imshow("Rotated", rotated)
cv2.waitKey(0)
cv2.destroyAllWindows()

### **Tarea A.7:** Guarda la imagen con ``cv2.imwrite()``

In [8]:
# TODO: Save the image to disk as 'salida_opcionA_1.png' using cv2.imwrite().
cv2.imwrite("salida_opcionA_1.png", rotated)

True

## **Apartado B: Segmentación por color**

El objetivo de este apartado es segmentar los colores naranja y blanco de las imágenes en la carpeta ``data``.

1. **Tarea B.1**. Defina y ejecute el método para cargar imágenes ``load_imgs()``.
2. **Tarea B.2.** Defina los métodos ``show_image()`` y ``write_image()`` para visualizar y guardar imágenes.
3. **Tarea B.3.** Cambia el espacio de color de las imágenes a uno donde la crominancia y la intensidad estén separados (HSV).
4. **Tarea B.4.** Segmenta los colores anaranjados.
5. **Tarea B.5.** Segmenta los colores blancos.
6. **Tarea B.6.** Junta las máscaras para cada imagen (naranja + blanco) y segmenta cada una de ellas.
7. **Tarea B.7.** Guarda las imágenes.


### **Tarea B.1:** Defina y ejecute el método para cargar imágenes ``load_images()``

In [20]:
def load_images(filenames: List) -> List:
    return [cv2.imread(filename) for filename in filenames]

In [10]:
# TODO Build a list containing the paths of all images in the data folder
imgs_path = []
for i in range(6):
    imgs_path.append(f"../data/00{i}.jpg")

imgs = load_images(imgs_path)

### **Tarea B.2**. Defina los métodos ``show_image()`` y ``write_image()`` para visualizar y guardar imágenes

In [11]:
# TODO Complete the method, use every argument
def show_image(img: np.array, img_name: str = "Image"):
    cv2.imshow(img_name, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

# TODO Complete the method, use every argument
def write_image(output_folder: str, img_name: str, img: np.array):
    img_path = os.path.join(output_folder, img_name)
    cv2.imwrite(img_path, img)
    

### **Tarea B.3:** Cambie el espacio de color de las imágenes a uno donde la crominancia y la intensidad estén separados (HSV)

In [12]:
# TODO Get a list with ìmgs in HSV color space
hsv_imgs = [cv2.cvtColor(img, cv2.COLOR_BGR2HSV) for img in imgs]

### **Tarea B.4:** Segmente los colores anaranjados

In [13]:
# TODO Define orange color range
light_orange = (1, 190, 200)
dark_orange = (255, 255, 255)

# TODO Compute a list that contains a mask (which should segment orange colors) for every image.

orange_masks = [cv2.inRange(hsv, light_orange, dark_orange) for hsv in hsv_imgs]

# TODO Compute a list that contains the result of multiplying the original image with its orange colors mask.
orange_segmented = [cv2.bitwise_and(img, img, mask = mask) for img, mask in zip(imgs, orange_masks)]

# TODO Show an original image
show_image(imgs[0], "Original")

# TODO Show a mask
show_image(orange_masks[0], "Mask")

# TODO Show a segmented image
show_image(orange_segmented[0], "Segmented")

### **Tarea B.5:** Segmente los colores blancos.

Para detectar el rango de blancos complete la siguiente celda y ejecutela para investigar el rango de valores necesarios.

In [14]:
# TODO Discover white color ranges
get_hsv_color_ranges(img)

# TODO Define white color range
light_white = (0, 0, 200)
dark_white = (180, 30, 255)

# TODO Compute a list that contains a mask (which should segment white colors) for every image.
white_masks = [cv2.inRange(hsv, light_white, dark_white) for hsv in hsv_imgs]


# TODO Compute a list that contains the result of multiplying the original image with its white colors mask.
white_segmented = [cv2.bitwise_and(img, img, mask=mask) for img, mask in zip(imgs, white_masks)]

# TODO Show an original image
show_image(imgs[0], "Original")

# TODO Show a mask
show_image(white_masks[0], "White Mask")

# TODO Show a segmented image
show_image(white_segmented[0], "White Segmented")

(hMin = 0 , sMin = 0, vMin = 0), (hMax = 255 , sMax = 255, vMax = 255)


### **Tarea B.6:** Junte las máscaras para cada imagen (naranja + blanco) y segmente cada una de ellas.

In [21]:
# TODO Join orange_masks and white_masks
fish_masks = [cv2.bitwise_or(om, wm) for om, wm in zip(orange_masks, white_masks)]
    
# TODO Compute a list that contains the result of multiplying the original image with its complete mask.
fish = [cv2.bitwise_and(img, img, mask=mask) for img, mask in zip(imgs, fish_masks)]

# TODO Show an original image
show_image(imgs[0], "Original")

# TODO Show a mask
show_image(fish_masks[0], "Fish Mask")

# TODO Show a segmented image
show_image(fish[0], "Fish Segmented")

### **Tarea B.7:** Guarde las imágenes

In [16]:
# TODO Define your output folder and save every fish image
output_folder = "output_fish"
os.makedirs(output_folder, exist_ok=True)
for i, f in enumerate(fish):
    img_name = f"fish_{i}.png"
    write_image(output_folder, img_name, f)

### **Pregunta B.1:** Segmente por color el logotipo de su marca favorita: descompóngalo en al menos 3 colores.

In [17]:
# Homework
filename = "../data/logo_olivia_rodrigo.jpg"
logo = cv2.imread(filename)
logo_hsv = cv2.cvtColor(logo, cv2.COLOR_BGR2HSV)

# vamos a descomponer la imagen en sus 3 colores principales: blanco, morado claro y morado oscuro
light_white, dark_white =   (0, 0, 200), (180, 30, 255)
light_purple1, dark_purple1 = (125, 70, 60), (140, 255, 255)
light_purple2, dark_purple2 = (140, 70, 60), (165, 255, 255)

# declaramos las máscaras para cada color
mask_white   = cv2.inRange(logo_hsv, light_white,   dark_white)
mask_purple1 = cv2.inRange(logo_hsv, light_purple1, dark_purple1)
mask_purple2 = cv2.inRange(logo_hsv, light_purple2, dark_purple2)

# y declaramos las segmentaciones
seg_white   = cv2.bitwise_and(logo, logo, mask=mask_white)
seg_purple1 = cv2.bitwise_and(logo, logo, mask=mask_purple1)
seg_purple2 = cv2.bitwise_and(logo, logo, mask=mask_purple2)


show_image(logo, "Original")

show_image(mask_white, "Mask - White")
show_image(seg_white,  "Segmented - White")

show_image(mask_purple1, "Mask - Light Purple")
show_image(seg_purple1,  "Segmented - Light Purple")

show_image(mask_purple2, "Mask - Dark Purple")
show_image(seg_purple2,  "Segmented - Dark Purple")


KeyboardInterrupt: 

### **Pregunta B.2:** ¿Qué ocurre si carga las imágenes con la función ``imageio.read()`` y luego la muestra con el método ``show_image()``? ¿A qué se debe este comportamiento?

In [18]:
def load_images(filenames: List) -> List:
    return [imageio.imread(filename) for filename in filenames]

# TODO Homework: Load images
question_imgs = load_images(imgs_path)


# TODO Homework: Show it
show_image(question_imgs[0], "Question Image")

# lo que ocurre es que la función en show_image se basa en el comando de cv2.imread(), 
# que lo que hace es leer las imágenes en formato BRG. Sin embargo, la función load_images usa imageio.imread(),
# que lee las imágenes en formato RGB. Por lo tanto, al intentar mostrar la imagen 
# se produce un error de color y los intercambia
# por eso al imprimir las imágenes del pez (naranja) sale en azul. 



C:\Users\crist\AppData\Local\Temp\ipykernel_19700\452123684.py:2: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  return [imageio.imread(filename) for filename in filenames]
